stages:
  - build
  - lint_format
  # - type_check
  - migrations
  - test
  - deploy

Build job:
  stage: build
  before_script:
    - cp ${ENV} .env
    - cp ${ENV_TEST} .env_test
    - docker image prune -f
  script:
    - docker build -t booking_api .

Linter job:
  stage: lint_format
  script:
    - docker run --rm --network my_network booking_api ruff check

Format job:
  stage: lint_format
  script:
    - docker run --rm --network my_network booking_api ruff format --check

# Type Checking:
#   stage: type_check
#   script:
#     - docker run --rm --network my_network booking_api ruff format --check
  
Migrations job:
  stage: migrations
  script:
    - docker run --rm --network my_network booking_api alembic upgrade head
  
Tests job:
  stage: test
  script:
    - docker run --rm --network my_network booking_api pytest
  
# Deploy job:
#   stage: deploy
#   before_script:
#     - docker compose -f docker-compose-ci.yml down
#   script:
#     - docker compose -f docker-compose-ci.yml up -d
#     - docker exec booking_nginx nginx -s reload
#   after_script:
#     - docker image prune -f
