services:
  booking_backend:
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - my_network
    env_file:
      - ".env"

  booking_cache_redis:
    image: redis:8.2.2
    ports:
      - "7379:6379"
    networks:
      - my_network
    env_file:
      - ".env"

  booking_celery_worker:
    build:
      context: .
    networks:
      - my_network
    env_file:
      - ".env"
    depends_on:
      - booking_backend
      - booking_cache_redis
    command: "celery --app=src.tasks.celery_base:celery_app worker --loglevel=INFO"

  booking_celery_beat:
    build:
      context: .
    networks:
      - my_network
    env_file:
      - ".env"
    depends_on:
      - booking_backend
      - booking_celery_worker
      - booking_cache_redis
    command: "celery --app=src.tasks.celery_base:celery_app beat -l INFO"

networks:
  my_network:
    external: true