# worker_processes 1;

events {
   # worker_connections 1000;    
}

http {
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=30r/s;
    
    server {
        listen 80;
        server_name _;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        # server_name _;

        location / {
            limit_req zone=mylimit;
            proxy_pass http://booking_backend:8000/;
        }

        # ssl_certificate path to sert;
        # ssl_certificate_key path to privare key;
        # include /etc/letsencrypt/options-ssl-nginx.conf;
        # ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    }
}